# Generated by Django 2.2.4 on 2019-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhar',
            name='casted',
            field=models.IntegerField(default=0),
        ),
    ]
