# Generated by Django 2.2.5 on 2019-09-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190919_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='people',
            new_name='bloc',
        ),
    ]
